# Dataset setup
text_exp: True
set: TextCLDataset
data: ./data/text/
num_tasks: 5
workers: 4
# text_tasks: []

# Model setup
model: TextCLModel
conv_type: StandardConv1d
bn_type: StandardBN1d
conv_init: signed_constant

# Forks
cnn_model: cnnstatic
emb_model: glove
epochs: 0
weight_epochs: 2
er_sparsity: normal
sparsity: 1

# Trainer
batch_size: 8
test_batch_size: 8
save: True
multigpu: [0]
log_interval: 10

# Optimizer setup
weight_opt: adam
train_weight_lr: 0.0005 # [0.0001, 0.001] for baseCL, [0.001, 0.0001] for Ind, [0.001/0.0001] for MTL, 
momentum: 0.9
wd: 0.0001

# Adaptation setup
adaptor: gt
adapt: True

