# Dataset setup
text_exp: False
data: ./data/
set: RandSplitCIFAR100
num_tasks: 20

# Model setup
model: GEMResNet18
conv_type: MultitaskMaskConv
bn_type: MultitaskNonAffineBN
conv_init: signed_constant
er_sparsity: normal
sparsity: 0.1

# Forks
epochs: 100
weight_epochs: 0
weight_mask_type: original

# Trainer
batch_size: 64
test_batch_size: 64
resume: False
save: True
multigpu: [0]
log_interval: 10

# Optimizer setup
mask_opt: adam
weight_opt: adam
lr: 0.01 # [0.001, 0.0001, 0.01] for worg, [0.01, 0.001, 0.0001] for wexc
train_weight_lr: 0.01 # [0.0001, 0.001] for w_org, [0.001, 0.01] for w_exc, 
momentum: 0.9
wd: 0.0001

# Adaptation setup
adaptor: gt
adapt: True
eval_ckpts: []
eval_all: True
